Bookstore. Milestone: Styling
CaptainBawa/Bookstore pull request #5
Opened 2023-05-19 15:00 UTC by CaptainBawa

### On this branch:

- I added the missing JSX elements to the project.
- I add styles.

2023-05-19 16:06 UTC, amejid requested changes
Hi @CaptainBawa, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

<img src="https://media0.giphy.com/media/t8YPf3ACKeouLzEIvr/giphy.gif"/>

## Highlights
- Linter checks passing :heavy_check_mark: 
- Correct workflow :heavy_check_mark: 
- Good layout :heavy_check_mark: 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-19 16:06 UTC, amejid commented on src/index.css
> +  background-color: rgb(224, 224, 224);
- [ ] I know it's been a while since we worked with a design guideline, but we have a guideline to follow for this one. Please make sure you are using the correct background color which is `#f5f6fa`. ✍️

2023-05-19 16:06 UTC, amejid commented on src/components/NavBar.js
>        </li>
- [ ] Please make sure you are using the correct font family, `Montserrat`, and the accurate color, `#0290ff`. Could you also use the right color for the navigation links to match the design guideline? Please reduce the height of your navigation bar. It looks a bit bigger when compared to the design. 😎️

**Your design**
![Screenshot from 2023-05-19 18-31-42](https://github.com/CaptainBawa/Bookstore/assets/17243325/68ac567b-1910-47a3-ae66-136a84d91ff8)

**Zeplin**
![Screenshot from 2023-05-19 18-31-26](https://github.com/CaptainBawa/Bookstore/assets/17243325/cf46ab06-713d-4644-a161-bf6c9420cd7f)

2023-05-19 16:06 UTC, amejid commented on src/components/BookList.js
> +              </li>
- [ ] Your circular progress bar is currently spinning non-stop which is not necessary per the project requirements. Please make it static, use the correct color, and also make sure you are using the correct font family for the percentage and the text `Completed`. I think the design uses `Montserrat`. Kindly use the correct color on the vertical line to the right of the text and make it a bit shorter to match the design. 🙂️


| Your design                                                             | Zeplin design                                         |
| --------------------------------------------------------------------------------| --------------------------------------------------------- |
|<img src="https://github.com/CaptainBawa/Bookstore/assets/17243325/7ab66c72-6b0a-48d7-b675-672a04112f72" width="300">|<img src="https://github.com/CaptainBawa/Bookstore/assets/17243325/8ea6c898-c29e-4cbf-b2ba-407f25697174" width="300">|

2023-05-19 16:06 UTC, amejid commented on src/components/BookList.js
> +              </li>
- [ ] Please use the correct font family for the texts in this part. I believe the design uses `RobotoSlab`. 🧐️


| Your design                                                             | Zeplin design                                         |
| --------------------------------------------------------------------------------| --------------------------------------------------------- |
|<img src="https://github.com/CaptainBawa/Bookstore/assets/17243325/76276ae1-0a2c-42e7-94f6-b1c6b7f5730a" width="300">|<img src="https://github.com/CaptainBawa/Bookstore/assets/17243325/6cd6b9cf-6ed1-447b-94f4-58979d1a8a80" width="300">|

2023-05-19 16:06 UTC, amejid commented on src/components/BookList.js
> +            </li>
- [ ] Kindly use the correct font families for the texts in this part. The book category uses `Montserrat` while the remaining texts use `RobotoSlab`. Please also align the text `COMMENTS` to the left according to the content above. Please adjust the gaps between the texts. 🤓️

| Your design                                                             | Zeplin design                                         |
| --------------------------------------------------------------------------------| --------------------------------------------------------- |
|<img src="https://github.com/CaptainBawa/Bookstore/assets/17243325/34284ddf-6b46-4cc6-acc1-798746e534b6" width="300">|<img src="https://github.com/CaptainBawa/Bookstore/assets/17243325/5738b9f2-e7b6-40d5-8fa8-cb166ef3507e" width="300">|

2023-05-19 16:06 UTC, amejid commented on src/components/BookForm.js
> +      <h1 className="form-h1">ADD NEW BOOK</h1>
- [ ] Kindly align the book form with the book cards above. Currently, your form is a bit to the left. ✍️

| Your design                                                             | Zeplin design                                         |
| --------------------------------------------------------------------------------| --------------------------------------------------------- |
|<img src="https://github.com/CaptainBawa/Bookstore/assets/17243325/3c390e12-6ad8-4231-b131-7d42fe192eba" width="300">|<img src="https://github.com/CaptainBawa/Bookstore/assets/17243325/4a075aa8-4c79-416c-8398-943247d45a52" width="300">|

2023-05-19 17:53 UTC, franclobo requested changes
Hi @CaptainBawa, 

# ♻️ Required Changes ♻️

![soClose](https://github.com/CaptainBawa/Bookstore/assets/58642949/910405d1-3142-4bfc-a525-36801b263da6)

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Highlights

- No linter errors ✔️ 
- Correct Git flow ✔️ 
- Descriptive PR ✔️ 
- Good UI ✔️ 


 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-19 17:53 UTC, franclobo commented on src/index.css
> +}
- [ ] I recommend creating a class to give the correct styles to the title and complete al the required changes by the last CR to approve this milestone. 👇🏽 

> Please make sure you are using the correct font family, Montserrat, and the accurate color, #0290ff. Could you also use the right color for the navigation links to match the design guideline? Please reduce the height of your navigation bar. It looks a bit bigger when compared to the design. 😎️

2023-05-19 17:53 UTC, franclobo commented on src/index.css
> +}
- [ ] As required by the previous code reviewer, please 🙏🏽 align the form to the rest of the content to look similar to the Zeplin design.

> Kindly align the book form with the book cards above. Currently, your form is a bit to the left. ✍️

2023-05-20 07:39 UTC, frank1738 approved these changes
Hi @CaptainBawa , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

<img src="https://media0.giphy.com/media/tIeCLkB8geYtW/giphy.gif"/>

## Highlights

✅ Correct use of Gitflow
✅ No linter error

## Optional suggestions

N/A

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-20 07:52 UTC, merged